version: '3.1'

services:
  postgres:
      container_name: marktplatz-order-service.postgres
      image: postgres:15
      ports:
        - "54322:5432"
      environment:
        POSTGRES_PASSWORD: postgres
